# Copyright 2025-2026 Inria

include_guard(GLOBAL)
cmake_minimum_required(VERSION 3.22)

#[============================================================================[
# `jrl_test_case`

```cmake
jrl_test_case(
    NAME <name>
    CODE <code_block>
    [STEPS <step> [<step> ...]]
    [WILL_FAIL]
    [PROPERTIES <prop> <value> ...]
)
```

**Type:** function


### Description
  Registers a CTest test that runs the given block of CMake code.

  Without `STEPS`, the code is written to a temporary script and run in a single
  `cmake -P` process. This is the default: fast, isolated, and enough for anything that does
  not depend on the CMake cache being written to disk.

  With `STEPS`, the code is inserted in a generated `LANGUAGES NONE` project which is
  configured once per step, all in the same build tree, the way a user re-runs
  `cmake -S . -B build` after toggling an option. Each step is a real `cmake` invocation, so
  the cache is written to disk and read back and what it keeps between two configures is
  really tested. No compiler is needed.

  Each step is registered as its own CTest test, named `<name> [step <n>]`, preceded by a
  `<name> [clean]` test wiping the build tree. They are chained with CTest fixtures, so they
  always run in order, a failing step names itself, and the steps after it are reported
  `Not Run` rather than failing in cascade against a half-configured tree. Running a single
  step with `ctest -R` pulls in the steps it depends on.

  In `STEPS` mode the code can use every jrl API plus the `expect_option()` helper, which
  reads the cache the way cmake-gui/ccmake would:

  ```cmake
  expect_option(<option_name> [VALUE <value>] [ADVANCED <0|1>])
  ```


### Arguments
* `NAME`: (OneValue) The name of the test case.
* `CODE`: (OneValue) The block of CMake code to execute. Must be quoted or in brackets `[[...]]`.
* `STEPS`: (MultiValue) One string of `cmake` command line arguments per configure step. Switches the test to a multi-configure project, one CTest test per step.
* `WILL_FAIL`: (Option) Shortcut for `PROPERTIES WILL_FAIL TRUE`. CTest will treat a non-zero exit as PASS. With `STEPS`, applies to the last step.
* `PROPERTIES`: (MultiValue) Key-value pairs forwarded verbatim to `set_tests_properties(... PROPERTIES ...)`. Use any CTest test property, e.g. `PASS_REGULAR_EXPRESSION "regex"`. With `STEPS`, applies to the last step.


### Example
```cmake
jrl_test_case(
    NAME "My variable check fails"
    WILL_FAIL
    CODE [[
        _jrl_check(DEFINED UNDEFINED_VAR)
    ]]
)

jrl_test_case(
    NAME "My option comes back when its condition does"
    CODE [[
        jrl_option(MY_OPTION "An option" ON CONDITION "MY_DEP" FALLBACK OFF)
        expect_option(MY_OPTION VALUE ${EXPECTED_VALUE} ADVANCED ${EXPECTED_ADVANCED})
    ]]
    STEPS
        "-DMY_DEP=OFF -DEXPECTED_VALUE=OFF -DEXPECTED_ADVANCED=1"
        "-DMY_DEP=ON -DEXPECTED_VALUE=ON -DEXPECTED_ADVANCED=0"
)
```
#]============================================================================]

# Project configured at every step of a STEPS test. Only @...@ placeholders are substituted,
# so the ${...} and $CACHE{...} references below reach the generated file untouched.
set(_JRL_TEST_CASE_PROJECT_TEMPLATE
    [==[
# Generated by jrl_test_case() - do not edit.
cmake_minimum_required(VERSION 3.22)
project(reconfigure_@test_id@ LANGUAGES NONE)

include("@jrl_path@")

# Check an option against what the CMake cache holds, which is what cmake-gui/ccmake shows.
function(expect_option option_name)
    cmake_parse_arguments(PARSE_ARGV 1 arg "" "VALUE;ADVANCED" "")

    if(DEFINED arg_UNPARSED_ARGUMENTS)
        message(FATAL_ERROR "expect_option: unexpected argument(s) '${arg_UNPARSED_ARGUMENTS}'")
    endif()

    # A GUI only shows BOOL entries: an INTERNAL one with the right value would pass every
    # check below while being invisible in cmake-gui/ccmake.
    get_property(type CACHE ${option_name} PROPERTY TYPE)
    if(NOT type STREQUAL "BOOL")
        message(FATAL_ERROR "Expected ${option_name} to be a BOOL cache entry, got '${type}'")
    endif()

    if(DEFINED arg_VALUE AND NOT "$CACHE{${option_name}}" STREQUAL "${arg_VALUE}")
        message(
            FATAL_ERROR
            "Expected ${option_name} to be '${arg_VALUE}', got '$CACHE{${option_name}}'"
        )
    endif()

    get_property(advanced CACHE ${option_name} PROPERTY ADVANCED)
    if(advanced)
        set(advanced 1)
    else()
        set(advanced 0)
    endif()
    if(DEFINED arg_ADVANCED AND NOT "${advanced}" STREQUAL "${arg_ADVANCED}")
        message(
            FATAL_ERROR
            "Expected ${option_name} ADVANCED to be '${arg_ADVANCED}', got '${advanced}'"
        )
    endif()
endfunction()

@arg_CODE@
]==]
)

function(jrl_test_case)
    set(options WILL_FAIL)
    set(oneValueArgs NAME CODE)
    set(multiValueArgs PROPERTIES STEPS)
    cmake_parse_arguments(PARSE_ARGV 0 arg "${options}" "${oneValueArgs}" "${multiValueArgs}")

    if(NOT arg_NAME)
        message(FATAL_ERROR "jrl_test_case requires a NAME argument.")
    endif()

    if(NOT arg_CODE)
        message(FATAL_ERROR "jrl_test_case requires a CODE argument.")
    endif()

    # Determine path to jrl.cmake
    set(jrl_path "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../../modules/jrl.cmake")
    cmake_path(ABSOLUTE_PATH jrl_path NORMALIZE)
    if(NOT EXISTS "${jrl_path}")
        message(FATAL_ERROR "jrl.cmake not found at expected path: ${jrl_path}")
    endif()

    if(arg_STEPS)
        string(SHA256 name_hash "${arg_NAME}")
        string(SUBSTRING "${name_hash}" 0 8 test_id)
        set(work_dir "${CMAKE_CURRENT_BINARY_DIR}/reconfigure/${test_id}")
        set(source_dir "${work_dir}/src")
        set(binary_dir "${work_dir}/build")

        # Write the project that gets configured over and over.
        string(CONFIGURE "${_JRL_TEST_CASE_PROJECT_TEMPLATE}" project_content @ONLY)
        file(WRITE "${source_dir}/CMakeLists.txt" "${project_content}")

        # One CTest test per step, chained through CTest fixtures. Fixtures, not DEPENDS:
        # DEPENDS only orders tests, it still runs a step whose predecessor failed.
        # FIXTURES_REQUIRED marks the rest of the chain "Not Run" instead, so a single real
        # failure does not turn into a cascade of confusing ones.
        set(clean_test "${arg_NAME} [clean]")
        add_test(
            NAME "${clean_test}"
            COMMAND "${CMAKE_COMMAND}" -E rm -rf "${binary_dir}"
        )
        # Start from a pristine build tree so the test does not depend on a previous run.
        set_tests_properties("${clean_test}" PROPERTIES FIXTURES_SETUP "${test_id}_0")

        set(step_index 0)
        foreach(step IN LISTS arg_STEPS)
            set(previous_index ${step_index})
            math(EXPR step_index "${step_index} + 1")
            separate_arguments(step_args NATIVE_COMMAND "${step}")

            set(step_test "${arg_NAME} [step ${step_index}]")
            add_test(
                NAME "${step_test}"
                COMMAND
                    "${CMAKE_COMMAND}" -S "${source_dir}" -B "${binary_dir}" -G "${CMAKE_GENERATOR}"
                    ${step_args}
            )
            set_tests_properties(
                "${step_test}"
                PROPERTIES
                    FIXTURES_REQUIRED "${test_id}_${previous_index}"
                    FIXTURES_SETUP "${test_id}_${step_index}"
            )
        endforeach()

        # The last step is the one carrying the assertion of interest.
        set(properties_test "${step_test}")
    else()
        # Write a temp script combining the include and the code, and run it in one process.
        string(SHA256 code_hash "${arg_CODE}")
        set(tmp_script "${CMAKE_CURRENT_BINARY_DIR}/tmp_jrl_test_case_${code_hash}.cmake")
        file(WRITE "${tmp_script}" "include(\"${jrl_path}\")\n${arg_CODE}")

        add_test(NAME "${arg_NAME}" COMMAND "${CMAKE_COMMAND}" -P "${tmp_script}")
        set(properties_test "${arg_NAME}")
    endif()

    if(arg_WILL_FAIL)
        set_tests_properties("${properties_test}" PROPERTIES WILL_FAIL TRUE)
    endif()
    if(arg_PROPERTIES)
        set_tests_properties("${properties_test}" PROPERTIES ${arg_PROPERTIES})
    endif()
endfunction()
