# Copyright 2026 Inria

# Finds CppADCodeGen (https://github.com/joaoleal/CppADCodeGen), defining cppadcg::cppadcg and cppad::cppad.

# An existing target (e.g. built in-tree) is enough, unless a version has to be checked below.
if(TARGET cppadcg::cppadcg AND NOT cppadcg_FIND_VERSION)
    set(cppadcg_FOUND TRUE)
    return()
endif()

find_path(cppadcg_INCLUDE_DIR NAMES cppad/cg.hpp)

mark_as_advanced(cppadcg_INCLUDE_DIR)

if(cppadcg_INCLUDE_DIR AND EXISTS "${cppadcg_INCLUDE_DIR}/cppad/cg/configure.hpp")
    # `#define CPPAD_CG_VERSION "cppadcg-2.5.0"`
    file(READ "${cppadcg_INCLUDE_DIR}/cppad/cg/configure.hpp" cppadcg_configure_hpp)
    string(
        REGEX MATCH "#[ \t]*define[ \t]+CPPAD_CG_VERSION[ \t]+\"cppadcg-([0-9.]+)\""
        _
        "${cppadcg_configure_hpp}"
    )
    set(cppadcg_VERSION "${CMAKE_MATCH_1}")
    unset(cppadcg_configure_hpp)
endif()

set(cppadcg_required_vars cppadcg_INCLUDE_DIR)

if(NOT TARGET cppad::cppad)
    find_path(cppad_INCLUDE_DIR NAMES cppad/configure.hpp)
    find_library(cppad_LIBRARY NAMES cppad_lib libcppad_lib)
    mark_as_advanced(cppad_INCLUDE_DIR cppad_LIBRARY)
    list(APPEND cppadcg_required_vars cppad_LIBRARY cppad_INCLUDE_DIR)
endif()

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(
    cppadcg
    REQUIRED_VARS ${cppadcg_required_vars}
    VERSION_VAR cppadcg_VERSION
)
unset(cppadcg_required_vars)

# Define cppad::cppad if not already defined.
if(cppadcg_FOUND AND NOT TARGET cppad::cppad)
    add_library(cppad::cppad UNKNOWN IMPORTED)
    set_target_properties(
        cppad::cppad
        PROPERTIES
            IMPORTED_LOCATION "${cppad_LIBRARY}"
            INTERFACE_INCLUDE_DIRECTORIES "${cppad_INCLUDE_DIR}"
            # cppad_lib dlopen()s the code generated by CppADCodeGen.
            INTERFACE_LINK_LIBRARIES "${CMAKE_DL_LIBS}"
    )
endif()

if(cppadcg_FOUND AND NOT TARGET cppadcg::cppadcg)
    add_library(cppadcg::cppadcg INTERFACE IMPORTED)
    set_target_properties(
        cppadcg::cppadcg
        PROPERTIES
            INTERFACE_INCLUDE_DIRECTORIES "${cppadcg_INCLUDE_DIR}"
            INTERFACE_VERSION "${cppadcg_VERSION}"
            INTERFACE_LINK_LIBRARIES cppad::cppad
    )
endif()
