# Copyright 2026 Inria

# Finds CppAD (https://cppad.readthedocs.io), which ships no config file, and defines cppad::cppad.

# An existing target (e.g. built in-tree) is enough, unless a version has to be checked below.
if(TARGET cppad::cppad AND NOT cppad_FIND_VERSION)
    set(cppad_FOUND TRUE)
    return()
endif()

find_path(cppad_INCLUDE_DIR NAMES cppad/configure.hpp)
find_library(cppad_LIBRARY NAMES cppad_lib libcppad_lib)

mark_as_advanced(cppad_INCLUDE_DIR cppad_LIBRARY)

if(cppad_INCLUDE_DIR)
    # `# define CPPAD_PACKAGE_STRING "cppad-20260000.0"`
    file(READ "${cppad_INCLUDE_DIR}/cppad/configure.hpp" cppad_configure_hpp)
    string(
        REGEX MATCH "#[ \t]*define[ \t]+CPPAD_PACKAGE_STRING[ \t]+\"cppad-([0-9.]+)\""
        _
        "${cppad_configure_hpp}"
    )
    set(cppad_VERSION "${CMAKE_MATCH_1}")
    unset(cppad_configure_hpp)
endif()

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(
    cppad
    REQUIRED_VARS cppad_LIBRARY cppad_INCLUDE_DIR
    VERSION_VAR cppad_VERSION
)

if(cppad_FOUND AND NOT TARGET cppad::cppad)
    add_library(cppad::cppad UNKNOWN IMPORTED)
    set_target_properties(
        cppad::cppad
        PROPERTIES
            IMPORTED_LOCATION "${cppad_LIBRARY}"
            VERSION "${cppad_VERSION}"
            INTERFACE_INCLUDE_DIRECTORIES "${cppad_INCLUDE_DIR}"
            # cppad_lib dlopen()s the code generated by CppADCodeGen.
            INTERFACE_LINK_LIBRARIES "${CMAKE_DL_LIBS}"
    )
endif()
